version: '3'

services:

  php:
    container_name: ${PREFIX}_php
    image: ${PREFIX}_php
    build: ./php

  fpm:
    container_name: ${PREFIX}_fpm
    image: ${PREFIX}_fpm
    build: ./fpm
    depends_on:
      - php
    restart: always
    expose:
      - 9000
    volumes:
      - ${SOURCE_DIR}:${TARGET_DIR}

  composer:
    container_name: ${PREFIX}_composer
    image: ${PREFIX}_composer
    build: ./composer
    depends_on:
      - php
    restart: always
    volumes:
      - ${SOURCE_DIR}:${TARGET_DIR}
    stdin_open: true
    tty: true

  nginx:
    container_name: ${PREFIX}_nginx
    image: ${PREFIX}_nginx
    build: ./nginx
    restart: always
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ${SOURCE_DIR}:${TARGET_DIR}
      - ./nginx/sites:/etc/nginx/conf.d
      - ./scripts/healthcheck/nginx.sh:/bin/healthcheck.sh
    links:
      - fpm
    stdin_open: true
    tty: true
    healthcheck:
      test: ['CMD', 'bash', '/bin/healthcheck.sh']
      interval: 10s
      timeout: 20s
      retries: 3
#      start-period: 10s

  varnish:
    container_name: ${PREFIX}_varnish
    depends_on:
      - nginx
    build: ./varnish
    links:
      - nginx
    ports:
      - "127.0.0.1:6081:6081"

  db:
    image: mariadb:10.4
    container_name: ${PREFIX}_db
    restart: always
    environment:
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ${DB_PATH_HOST}:/var/lib/mysql
      - ./scripts/healthcheck/mysql.sh:/bin/healthcheck.sh
    healthcheck:
      test: ['CMD', 'bash', '/bin/healthcheck.sh']
      interval: 10s
      timeout: 20s
      retries: 3

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ${PREFIX}_phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    depends_on:
      - db

  elasticsearch:
    image: elasticsearch:7.8.1
    container_name: ${PREFIX}_elasticsearch
#    networks:
#      - magento-demo-network
    volumes:
      - ./scripts/healthcheck/es.sh:/bin/healthcheck.sh
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
    healthcheck:
      test: ['CMD', 'bash', '/bin/healthcheck.sh']
      interval: 10s
      timeout: 20s
      retries: 3

  redis:
    image: redis:latest
    container_name: ${PREFIX}_redis
    working_dir: ${APP_PATH_CONTAINER}
    restart: always
    ports:
      - "127.0.0.1:6380:6379"
    volumes:
      - ${REDIS_PATH_CONF}:/redis.conf
      - ./scripts/healthcheck/redis.sh:/bin/healthcheck.sh
    healthcheck:
      test: ['CMD', 'bash', '/bin/healthcheck.sh']
      interval: 10s
      timeout: 20s
      retries: 3
    command: [ "redis-server", "/redis.conf" ]

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: ${PREFIX}_rabbitmq
    ports:
      - "15674:15672"
      - "5674:5672"
    volumes:
      - ${RABBIT_MQ_DATA}:/var/lib/rabbitmq/
      - ${RABBIT_MQ_LOGS}:/var/log/rabbitmq
      - ./scripts/healthcheck/rabbitmq.sh:/bin/healthcheck.sh
    healthcheck:
      test: ['CMD', 'bash', '/bin/healthcheck.sh']
      interval: 5s
      timeout: 10s
      retries: 3
