version: '3'

services:

  php:
    container_name: ${PREFIX}_php
    image: ${PREFIX}_php
    build: ./php

  fpm:
    container_name: ${PREFIX}_fpm
    image: ${PREFIX}_fpm
    build: ./fpm
    depends_on:
      - php
    restart: always
    expose:
      - 9000
    volumes:
      - ${SOURCE_DIR}:${TARGET_DIR}

  composer:
    container_name: ${PREFIX}_composer
    image: ${PREFIX}_composer
    build: ./composer
    depends_on:
      - php
    restart: always
    volumes:
      - ${SOURCE_DIR}:${TARGET_DIR}
    stdin_open: true
    tty: true

  nginx:
    container_name: ${PREFIX}_nginx
    image: ${PREFIX}_nginx
    build: ./nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ${SOURCE_DIR}:${TARGET_DIR}
      - ./nginx/sites:/etc/nginx/conf.d
      - ./nginx/healthcheck.sh:/bin/healthcheck.sh
    links:
      - fpm
    stdin_open: true
    tty: true
    healthcheck:
      test: ['CMD', 'bash', '/bin/healthcheck.sh']
      interval: 10s
      timeout: 20s
      retries: 3
#      start_period: 10s

#  mysql:
#    image: mysql:5.7
#    container_name: ${PREFIX}_mysql
#    ports:
#      - "3307:3306"
#    command: --default-authentication-plugin=mysql_native_password
#    restart: always
#    environment:
#      MYSQL_ROOT_USER: root
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: magento

  db:
    image: mariadb:10.4
    container_name: ${PREFIX}_db
    restart: always
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=q1w2e3r4
    volumes:
      - ${DB_PATH_HOST}:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    depends_on:
      - db

  elasticsearch:
    image: elasticsearch:7.8.1
    container_name: ${PREFIX}_elasticsearch
#    networks:
#      - magento-demo-network
    volumes:
      - ./elasticsearch/healthcheck.sh:/bin/healthcheck.sh
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
    healthcheck:
      test: ['CMD', 'bash', '/bin/healthcheck.sh']
      interval: 10s
      timeout: 20s
      retries: 3
#      start_period: 10s

  redis:
    image: redis:latest
    container_name: ${PREFIX}_redis
    working_dir: ${APP_PATH_CONTAINER}
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - ${REDIS_PATH_CONF}:/redis.conf
    command: [ "redis-server", "/redis.conf" ]

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: ${PREFIX}_rabbitmq
    ports:
      - "15673:15672"
      - "5673:5672"
    volumes:
      - ${RABBIT_MQ_DATA}:/var/lib/rabbitmq/
      - ${RABBIT_MQ_LOGS}:/var/log/rabbitmq